require('../src/data.js');
const inputFilter = [
    {
        version: '6.24.1',
        id: 'Aatrox',
        key: '266',
        name: 'Aatrox',
        title: 'the Darkin Blade',
        img:
            'https://www.masterypoints.com/assets/img/lol/champion_icons/Aatrox.png',
        splash:
            'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aatrox_0.jpg',
        blurb:
            'Aatrox is a legendary warrior, one of only five that remain of an ancient race known as the Darkin. He wields his massive blade with grace and poise, slicing through legions in a style that is hypnotic to behold. With each foe felled, Aatrox',
        info: {
            attack: 8,
            defense: 4,
            magic: 3,
            difficulty: 4
        },
        tags: ['Fighter', 'Tank'],
        partype: 'BloodWell',
        stats: {
            hp: 537.8,
            hpperlevel: 85,
            mp: 105.6,
            mpperlevel: 45,
            movespeed: 345,
            armor: 24.384,
            armorperlevel: 3.8,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 150,
            hpregen: 6.59,
            hpregenperlevel: 0.5,
            mpregen: 0,
            mpregenperlevel: 0,
            crit: 0,
            critperlevel: 0,
            attackdamage: 60.376,
            attackdamageperlevel: 3.2,
            attackspeedoffset: -0.04,
            attackspeedperlevel: 3
        }
    },
    {
        version: '6.24.1',
        id: 'Ahri',
        key: '103',
        name: 'Ahri',
        title: 'the Nine-Tailed Fox',
        img:
            'https://www.masterypoints.com/assets/img/lol/champion_icons/Ahri.png',
        splash:
            'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_0.jpg',
        blurb:
            'Unlike other foxes that roamed the woods of southern Ionia, Ahri had always felt a strange connection to the magical world around her; a connection that was somehow incomplete. Deep inside, she felt the skin she had been born into was an ill fit for ...',
        info: {
            attack: 3,
            defense: 4,
            magic: 8,
            difficulty: 5
        },
        tags: ['Mage', 'Assassin'],
        partype: 'MP',
        stats: {
            hp: 514.4,
            hpperlevel: 80,
            mp: 334,
            mpperlevel: 50,
            movespeed: 330,
            armor: 20.88,
            armorperlevel: 3.5,
            spellblock: 30,
            spellblockperlevel: 0,
            attackrange: 550,
            hpregen: 6.505,
            hpregenperlevel: 0.6,
            mpregen: 6,
            mpregenperlevel: 0.8,
            crit: 0,
            critperlevel: 0,
            attackdamage: 53.04,
            attackdamageperlevel: 3,
            attackspeedoffset: -0.065,
            attackspeedperlevel: 2
        }
    },
    {
        version: '6.24.1',
        id: 'Akali',
        key: '84',
        name: 'Akali',
        title: 'the Fist of Shadow',
        img:
            'https://www.masterypoints.com/assets/img/lol/champion_icons/Akali.png',
        splash:
            'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akali_0.jpg',
        blurb:
            'There exists an ancient order originating in the Ionian Isles dedicated to the preservation of balance. Order, chaos, light, darkness -- all things must exist in perfect harmony for such is the way of the universe. This order is known as the Kinkou ...',
        info: {
            attack: 5,
            defense: 3,
            magic: 8,
            difficulty: 7
        },
        tags: ['Assassin'],
        partype: 'Energy',
        stats: {
            hp: 587.8,
            hpperlevel: 85,
            mp: 200,
            mpperlevel: 0,
            movespeed: 350,
            armor: 26.38,
            armorperlevel: 3.5,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 125,
            hpregen: 8.34,
            hpregenperlevel: 0.65,
            mpregen: 50,
            mpregenperlevel: 0,
            crit: 0,
            critperlevel: 0,
            attackdamage: 58.376,
            attackdamageperlevel: 3.2,
            attackspeedoffset: -0.1,
            attackspeedperlevel: 3.1
        }
    }

];
const filterType = 'Assassin';
const outputFilter = [
    {
        version: '6.24.1',
        id: 'Ahri',
        key: '103',
        name: 'Ahri',
        title: 'the Nine-Tailed Fox',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Ahri.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_0.jpg',
        blurb: 'Unlike other foxes that roamed the woods of southern Ionia, Ahri had always felt a strange connection to the magical world around her; a connection that was somehow incomplete. Deep inside, she felt the skin she had been born into was an ill fit for ...',
        info: { attack: 3, defense: 4, magic: 8, difficulty: 5 },
        tags: ['Mage', 'Assassin'],
        partype: 'MP',
        stats:
        {
            hp: 514.4,
            hpperlevel: 80,
            mp: 334,
            mpperlevel: 50,
            movespeed: 330,
            armor: 20.88,
            armorperlevel: 3.5,
            spellblock: 30,
            spellblockperlevel: 0,
            attackrange: 550,
            hpregen: 6.505,
            hpregenperlevel: 0.6,
            mpregen: 6,
            mpregenperlevel: 0.8,
            crit: 0,
            critperlevel: 0,
            attackdamage: 53.04,
            attackdamageperlevel: 3,
            attackspeedoffset: -0.065,
            attackspeedperlevel: 2
        }
    },
    {
        version: '6.24.1',
        id: 'Akali',
        key: '84',
        name: 'Akali',
        title: 'the Fist of Shadow',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Akali.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akali_0.jpg',
        blurb: 'There exists an ancient order originating in the Ionian Isles dedicated to the preservation of balance. Order, chaos, light, darkness -- all things must exist in perfect harmony for such is the way of the universe. This order is known as the Kinkou ...',
        info: { attack: 5, defense: 3, magic: 8, difficulty: 7 },
        tags: ['Assassin'],
        partype: 'Energy',
        stats:
        {
            hp: 587.8,
            hpperlevel: 85,
            mp: 200,
            mpperlevel: 0,
            movespeed: 350,
            armor: 26.38,
            armorperlevel: 3.5,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 125,
            hpregen: 8.34,
            hpregenperlevel: 0.65,
            mpregen: 50,
            mpregenperlevel: 0,
            crit: 0,
            critperlevel: 0,
            attackdamage: 58.376,
            attackdamageperlevel: 3.2,
            attackspeedoffset: -0.1,
            attackspeedperlevel: 3.1
        }
    }];
const sortByType = 'name';
const sortOrderAsc = 1;
const inputOrder = [
    {
        version: '6.24.1',
        id: 'Riven',
        key: '92',
        name: 'Riven',
        title: 'the Exile',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Riven.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Riven_0.jpg',
        blurb: '\'\'There is a place between war and murder in which our demons lurk.\'\'<br><br>In Noxus, any citizen may rise to power regardless of race, gender, or social standing - strength is all that matters. It was with committed faith in this ideal that Riven ...',
        info: { attack: 8, defense: 5, magic: 1, difficulty: 8 },
        tags: ['Fighter', 'Assassin'],
        partype: 'None',
        stats:
        {
            hp: 558.48,
            hpperlevel: 86,
            mp: 0,
            mpperlevel: 0,
            movespeed: 340,
            armor: 24.376,
            armorperlevel: 3.2,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 125,
            hpregen: 5.34,
            hpregenperlevel: 0.5,
            mpregen: 0,
            mpregenperlevel: 0,
            crit: 0,
            critperlevel: 0,
            attackdamage: 56.04,
            attackdamageperlevel: 3,
            attackspeedoffset: 0,
            attackspeedperlevel: 3.5
        }
    },
    {
        version: '6.24.1',
        id: 'Singed',
        key: '27',
        name: 'Singed',
        title: 'the Mad Chemist',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Singed.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Signed_0.jpg',
        blurb: 'Singed descended from a long line of Zaun\'s revered chemists. Even in his youth, his talent for concocting potions far outstripped that of his peers, and he quickly distinguished himself from his less extraordinary chemist compatriots. It came as no ...',
        info: { attack: 4, defense: 8, magic: 7, difficulty: 5 },
        tags: ['Tank', 'Fighter'],
        partype: 'MP',
        stats:
        {
            hp: 542.76,
            hpperlevel: 82,
            mp: 290.6,
            mpperlevel: 45,
            movespeed: 345,
            armor: 27.88,
            armorperlevel: 3.5,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 125,
            hpregen: 8.02,
            hpregenperlevel: 0.55,
            mpregen: 7.52,
            mpregenperlevel: 0.55,
            crit: 0,
            critperlevel: 0,
            attackdamage: 62.32,
            attackdamageperlevel: 3.375,
            attackspeedoffset: 0.02,
            attackspeedperlevel: 1.81
        }
    },
    {
        version: '6.24.1',
        id: 'Blitzcrank',
        key: '53',
        name: 'Blitzcrank',
        title: 'the Great Steam Golem',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Blitzcrank.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Blitzcranck_0.jpg',
        blurb: 'Zaun is a place where both magic and science have gone awry, and the unchecked nature of experimentation has taken its toll. However, Zaun\'s lenient restrictions allow their researchers and inventors the leeway to push the bounds of science at an ...',
        info: { attack: 4, defense: 8, magic: 5, difficulty: 4 },
        tags: ['Tank', 'Fighter'],
        partype: 'MP',
        stats:
        {
            hp: 582.6,
            hpperlevel: 95,
            mp: 267.2,
            mpperlevel: 40,
            movespeed: 325,
            armor: 24.38,
            armorperlevel: 4,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 125,
            hpregen: 8.51,
            hpregenperlevel: 0.75,
            mpregen: 8.5,
            mpregenperlevel: 0.8,
            crit: 0,
            critperlevel: 0,
            attackdamage: 61.54,
            attackdamageperlevel: 3.5,
            attackspeedoffset: 0,
            attackspeedperlevel: 1.13
        }
    },
    {
        version: '6.24.1',
        id: 'Morgana',
        key: '25',
        name: 'Morgana',
        title: 'Fallen Angel',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Morgana.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Morgana_0.jpg',
        blurb: 'There is a world far away populated by graceful and beautiful winged beings gifted with immortality, where an ancient conflict still rages. Like so many conflicts, this war split families. One side proclaimed themselves as beings of perfect order and ...',
        info: { attack: 1, defense: 6, magic: 8, difficulty: 1 },
        tags: ['Mage', 'Support'],
        partype: 'MP',
        stats:
        {
            hp: 547.48,
            hpperlevel: 86,
            mp: 340.8,
            mpperlevel: 60,
            movespeed: 335,
            armor: 25.384,
            armorperlevel: 3.8,
            spellblock: 30,
            spellblockperlevel: 0,
            attackrange: 450,
            hpregen: 5.705,
            hpregenperlevel: 0.6,
            mpregen: 8.5,
            mpregenperlevel: 0.8,
            crit: 0,
            critperlevel: 0,
            attackdamage: 55.46,
            attackdamageperlevel: 3.5,
            attackspeedoffset: 0,
            attackspeedperlevel: 1.53
        }
    },
    {
        version: '6.24.1',
        id: 'Zac',
        key: '154',
        name: 'Zac',
        title: 'the Secret Weapon',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Zac.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zac_0.jpg',
        blurb: 'Zac is the product of a Zaun experiment to manufacture a hexchem-engineered supersoldier - the Zaun Amorphous Combatant. Combining brute strength with limitless flexibility, he is a versatile juggernaut: a creative fighter who bounces over obstacles ...',
        info: { attack: 3, defense: 7, magic: 7, difficulty: 8 },
        tags: ['Tank', 'Fighter'],
        partype: 'None',
        stats:
        {
            hp: 614.6,
            hpperlevel: 95,
            mp: 0,
            mpperlevel: 0,
            movespeed: 340,
            armor: 23.88,
            armorperlevel: 3.5,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 175,
            hpregen: 7.92,
            hpregenperlevel: 0.55,
            mpregen: 0,
            mpregenperlevel: 0,
            crit: 0,
            critperlevel: 0,
            attackdamage: 59.67,
            attackdamageperlevel: 3.375,
            attackspeedoffset: -0.02,
            attackspeedperlevel: 1.6
        }
    },
    {
        version: '6.24.1',
        id: 'Amumu',
        key: '32',
        name: 'Amumu',
        title: 'the Sad Mummy',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Amumu.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Amumu_0.jpg',
        blurb: '\'\'Solitude can be lonelier than death.\'\'<br><br>A lonely and melancholy soul from ancient Shurima, Amumu roams the world in search of a friend. Cursed by an ancient spell, he is doomed to remain alone forever, as his touch is death and his affection ...',
        info: { attack: 2, defense: 6, magic: 8, difficulty: 3 },
        tags: ['Tank', 'Mage'],
        partype: 'MP',
        stats:
        {
            hp: 613.12,
            hpperlevel: 84,
            mp: 287.2,
            mpperlevel: 40,
            movespeed: 335,
            armor: 23.544,
            armorperlevel: 3.8,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 125,
            hpregen: 8.875,
            hpregenperlevel: 0.85,
            mpregen: 7.38,
            mpregenperlevel: 0.525,
            crit: 0,
            critperlevel: 0,
            attackdamage: 53.384,
            attackdamageperlevel: 3.8,
            attackspeedoffset: -0.02,
            attackspeedperlevel: 2.18
        }
    },
    {
        version: '6.24.1',
        id: 'Singed',
        key: '27',
        name: 'Singed',
        title: 'the Mad Chemist',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Singed.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Signed_0.jpg',
        blurb: 'Singed descended from a long line of Zaun\'s revered chemists. Even in his youth, his talent for concocting potions far outstripped that of his peers, and he quickly distinguished himself from his less extraordinary chemist compatriots. It came as no ...',
        info: { attack: 4, defense: 8, magic: 7, difficulty: 5 },
        tags: ['Tank', 'Fighter'],
        partype: 'MP',
        stats:
        {
            hp: 542.76,
            hpperlevel: 82,
            mp: 290.6,
            mpperlevel: 45,
            movespeed: 345,
            armor: 27.88,
            armorperlevel: 3.5,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 125,
            hpregen: 8.02,
            hpregenperlevel: 0.55,
            mpregen: 7.52,
            mpregenperlevel: 0.55,
            crit: 0,
            critperlevel: 0,
            attackdamage: 62.32,
            attackdamageperlevel: 3.375,
            attackspeedoffset: 0.02,
            attackspeedperlevel: 1.81
        }
    }, 
    {
        version: '6.24.1',
        id: 'Blitzcrank',
        key: '53',
        name: 'Blitzcrank',
        title: 'the Great Steam Golem',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Blitzcrank.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Blitzcranck_0.jpg',
        blurb: 'Zaun is a place where both magic and science have gone awry, and the unchecked nature of experimentation has taken its toll. However, Zaun\'s lenient restrictions allow their researchers and inventors the leeway to push the bounds of science at an ...',
        info: { attack: 4, defense: 8, magic: 5, difficulty: 4 },
        tags: ['Tank', 'Fighter'],
        partype: 'MP',
        stats:
        {
            hp: 582.6,
            hpperlevel: 95,
            mp: 267.2,
            mpperlevel: 40,
            movespeed: 325,
            armor: 24.38,
            armorperlevel: 4,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 125,
            hpregen: 8.51,
            hpregenperlevel: 0.75,
            mpregen: 8.5,
            mpregenperlevel: 0.8,
            crit: 0,
            critperlevel: 0,
            attackdamage: 61.54,
            attackdamageperlevel: 3.5,
            attackspeedoffset: 0,
            attackspeedperlevel: 1.13
        }
    }
];
const outputOrderAsc = [
    {
        version: '6.24.1',
        id: 'Amumu',
        key: '32',
        name: 'Amumu',
        title: 'the Sad Mummy',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Amumu.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Amumu_0.jpg',
        blurb: '\'\'Solitude can be lonelier than death.\'\'<br><br>A lonely and melancholy soul from ancient Shurima, Amumu roams the world in search of a friend. Cursed by an ancient spell, he is doomed to remain alone forever, as his touch is death and his affection ...',
        info: { attack: 2, defense: 6, magic: 8, difficulty: 3 },
        tags: ['Tank', 'Mage'],
        partype: 'MP',
        stats:
        {
            hp: 613.12,
            hpperlevel: 84,
            mp: 287.2,
            mpperlevel: 40,
            movespeed: 335,
            armor: 23.544,
            armorperlevel: 3.8,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 125,
            hpregen: 8.875,
            hpregenperlevel: 0.85,
            mpregen: 7.38,
            mpregenperlevel: 0.525,
            crit: 0,
            critperlevel: 0,
            attackdamage: 53.384,
            attackdamageperlevel: 3.8,
            attackspeedoffset: -0.02,
            attackspeedperlevel: 2.18
        }
    },
    {
        version: '6.24.1',
        id: 'Blitzcrank',
        key: '53',
        name: 'Blitzcrank',
        title: 'the Great Steam Golem',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Blitzcrank.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Blitzcranck_0.jpg',
        blurb: 'Zaun is a place where both magic and science have gone awry, and the unchecked nature of experimentation has taken its toll. However, Zaun\'s lenient restrictions allow their researchers and inventors the leeway to push the bounds of science at an ...',
        info: { attack: 4, defense: 8, magic: 5, difficulty: 4 },
        tags: ['Tank', 'Fighter'],
        partype: 'MP',
        stats:
        {
            hp: 582.6,
            hpperlevel: 95,
            mp: 267.2,
            mpperlevel: 40,
            movespeed: 325,
            armor: 24.38,
            armorperlevel: 4,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 125,
            hpregen: 8.51,
            hpregenperlevel: 0.75,
            mpregen: 8.5,
            mpregenperlevel: 0.8,
            crit: 0,
            critperlevel: 0,
            attackdamage: 61.54,
            attackdamageperlevel: 3.5,
            attackspeedoffset: 0,
            attackspeedperlevel: 1.13
        }
    },
    {
        version: '6.24.1',
        id: 'Blitzcrank',
        key: '53',
        name: 'Blitzcrank',
        title: 'the Great Steam Golem',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Blitzcrank.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Blitzcranck_0.jpg',
        blurb: 'Zaun is a place where both magic and science have gone awry, and the unchecked nature of experimentation has taken its toll. However, Zaun\'s lenient restrictions allow their researchers and inventors the leeway to push the bounds of science at an ...',
        info: { attack: 4, defense: 8, magic: 5, difficulty: 4 },
        tags: ['Tank', 'Fighter'],
        partype: 'MP',
        stats:
        {
            hp: 582.6,
            hpperlevel: 95,
            mp: 267.2,
            mpperlevel: 40,
            movespeed: 325,
            armor: 24.38,
            armorperlevel: 4,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 125,
            hpregen: 8.51,
            hpregenperlevel: 0.75,
            mpregen: 8.5,
            mpregenperlevel: 0.8,
            crit: 0,
            critperlevel: 0,
            attackdamage: 61.54,
            attackdamageperlevel: 3.5,
            attackspeedoffset: 0,
            attackspeedperlevel: 1.13
        }
    },
    {
        version: '6.24.1',
        id: 'Morgana',
        key: '25',
        name: 'Morgana',
        title: 'Fallen Angel',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Morgana.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Morgana_0.jpg',
        blurb: 'There is a world far away populated by graceful and beautiful winged beings gifted with immortality, where an ancient conflict still rages. Like so many conflicts, this war split families. One side proclaimed themselves as beings of perfect order and ...',
        info: { attack: 1, defense: 6, magic: 8, difficulty: 1 },
        tags: ['Mage', 'Support'],
        partype: 'MP',
        stats:
        {
            hp: 547.48,
            hpperlevel: 86,
            mp: 340.8,
            mpperlevel: 60,
            movespeed: 335,
            armor: 25.384,
            armorperlevel: 3.8,
            spellblock: 30,
            spellblockperlevel: 0,
            attackrange: 450,
            hpregen: 5.705,
            hpregenperlevel: 0.6,
            mpregen: 8.5,
            mpregenperlevel: 0.8,
            crit: 0,
            critperlevel: 0,
            attackdamage: 55.46,
            attackdamageperlevel: 3.5,
            attackspeedoffset: 0,
            attackspeedperlevel: 1.53
        }
    },
    {
        version: '6.24.1',
        id: 'Riven',
        key: '92',
        name: 'Riven',
        title: 'the Exile',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Riven.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Riven_0.jpg',
        blurb: '\'\'There is a place between war and murder in which our demons lurk.\'\'<br><br>In Noxus, any citizen may rise to power regardless of race, gender, or social standing - strength is all that matters. It was with committed faith in this ideal that Riven ...',
        info: { attack: 8, defense: 5, magic: 1, difficulty: 8 },
        tags: ['Fighter', 'Assassin'],
        partype: 'None',
        stats:
        {
            hp: 558.48,
            hpperlevel: 86,
            mp: 0,
            mpperlevel: 0,
            movespeed: 340,
            armor: 24.376,
            armorperlevel: 3.2,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 125,
            hpregen: 5.34,
            hpregenperlevel: 0.5,
            mpregen: 0,
            mpregenperlevel: 0,
            crit: 0,
            critperlevel: 0,
            attackdamage: 56.04,
            attackdamageperlevel: 3,
            attackspeedoffset: 0,
            attackspeedperlevel: 3.5
        }
    },
    {
        version: '6.24.1',
        id: 'Singed',
        key: '27',
        name: 'Singed',
        title: 'the Mad Chemist',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Singed.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Signed_0.jpg',
        blurb: 'Singed descended from a long line of Zaun\'s revered chemists. Even in his youth, his talent for concocting potions far outstripped that of his peers, and he quickly distinguished himself from his less extraordinary chemist compatriots. It came as no ...',
        info: { attack: 4, defense: 8, magic: 7, difficulty: 5 },
        tags: ['Tank', 'Fighter'],
        partype: 'MP',
        stats:
        {
            hp: 542.76,
            hpperlevel: 82,
            mp: 290.6,
            mpperlevel: 45,
            movespeed: 345,
            armor: 27.88,
            armorperlevel: 3.5,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 125,
            hpregen: 8.02,
            hpregenperlevel: 0.55,
            mpregen: 7.52,
            mpregenperlevel: 0.55,
            crit: 0,
            critperlevel: 0,
            attackdamage: 62.32,
            attackdamageperlevel: 3.375,
            attackspeedoffset: 0.02,
            attackspeedperlevel: 1.81
        }
    },
    {
        version: '6.24.1',
        id: 'Singed',
        key: '27',
        name: 'Singed',
        title: 'the Mad Chemist',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Singed.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Signed_0.jpg',
        blurb: 'Singed descended from a long line of Zaun\'s revered chemists. Even in his youth, his talent for concocting potions far outstripped that of his peers, and he quickly distinguished himself from his less extraordinary chemist compatriots. It came as no ...',
        info: { attack: 4, defense: 8, magic: 7, difficulty: 5 },
        tags: ['Tank', 'Fighter'],
        partype: 'MP',
        stats:
        {
            hp: 542.76,
            hpperlevel: 82,
            mp: 290.6,
            mpperlevel: 45,
            movespeed: 345,
            armor: 27.88,
            armorperlevel: 3.5,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 125,
            hpregen: 8.02,
            hpregenperlevel: 0.55,
            mpregen: 7.52,
            mpregenperlevel: 0.55,
            crit: 0,
            critperlevel: 0,
            attackdamage: 62.32,
            attackdamageperlevel: 3.375,
            attackspeedoffset: 0.02,
            attackspeedperlevel: 1.81
        }
    },
    {
        version: '6.24.1',
        id: 'Zac',
        key: '154',
        name: 'Zac',
        title: 'the Secret Weapon',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Zac.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zac_0.jpg',
        blurb: 'Zac is the product of a Zaun experiment to manufacture a hexchem-engineered supersoldier - the Zaun Amorphous Combatant. Combining brute strength with limitless flexibility, he is a versatile juggernaut: a creative fighter who bounces over obstacles ...',
        info: { attack: 3, defense: 7, magic: 7, difficulty: 8 },
        tags: ['Tank', 'Fighter'],
        partype: 'None',
        stats:
        {
            hp: 614.6,
            hpperlevel: 95,
            mp: 0,
            mpperlevel: 0,
            movespeed: 340,
            armor: 23.88,
            armorperlevel: 3.5,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 175,
            hpregen: 7.92,
            hpregenperlevel: 0.55,
            mpregen: 0,
            mpregenperlevel: 0,
            crit: 0,
            critperlevel: 0,
            attackdamage: 59.67,
            attackdamageperlevel: 3.375,
            attackspeedoffset: -0.02,
            attackspeedperlevel: 1.6
        }
    },
];
const sortOrderDesc = -1;
const inputOrder2 = [
    {
        version: '6.24.1',
        id: 'Riven',
        key: '92',
        name: 'Riven',
        title: 'the Exile',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Riven.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Riven_0.jpg',
        blurb: '\'\'There is a place between war and murder in which our demons lurk.\'\'<br><br>In Noxus, any citizen may rise to power regardless of race, gender, or social standing - strength is all that matters. It was with committed faith in this ideal that Riven ...',
        info: { attack: 8, defense: 5, magic: 1, difficulty: 8 },
        tags: ['Fighter', 'Assassin'],
        partype: 'None',
        stats:
        {
            hp: 558.48,
            hpperlevel: 86,
            mp: 0,
            mpperlevel: 0,
            movespeed: 340,
            armor: 24.376,
            armorperlevel: 3.2,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 125,
            hpregen: 5.34,
            hpregenperlevel: 0.5,
            mpregen: 0,
            mpregenperlevel: 0,
            crit: 0,
            critperlevel: 0,
            attackdamage: 56.04,
            attackdamageperlevel: 3,
            attackspeedoffset: 0,
            attackspeedperlevel: 3.5
        }
    },
    {
        version: '6.24.1',
        id: 'Morgana',
        key: '25',
        name: 'Morgana',
        title: 'Fallen Angel',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Morgana.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Morgana_0.jpg',
        blurb: 'There is a world far away populated by graceful and beautiful winged beings gifted with immortality, where an ancient conflict still rages. Like so many conflicts, this war split families. One side proclaimed themselves as beings of perfect order and ...',
        info: { attack: 1, defense: 6, magic: 8, difficulty: 1 },
        tags: ['Mage', 'Support'],
        partype: 'MP',
        stats:
        {
            hp: 547.48,
            hpperlevel: 86,
            mp: 340.8,
            mpperlevel: 60,
            movespeed: 335,
            armor: 25.384,
            armorperlevel: 3.8,
            spellblock: 30,
            spellblockperlevel: 0,
            attackrange: 450,
            hpregen: 5.705,
            hpregenperlevel: 0.6,
            mpregen: 8.5,
            mpregenperlevel: 0.8,
            crit: 0,
            critperlevel: 0,
            attackdamage: 55.46,
            attackdamageperlevel: 3.5,
            attackspeedoffset: 0,
            attackspeedperlevel: 1.53
        }
    },
    {
        version: '6.24.1',
        id: 'Zac',
        key: '154',
        name: 'Zac',
        title: 'the Secret Weapon',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Zac.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zac_0.jpg',
        blurb: 'Zac is the product of a Zaun experiment to manufacture a hexchem-engineered supersoldier - the Zaun Amorphous Combatant. Combining brute strength with limitless flexibility, he is a versatile juggernaut: a creative fighter who bounces over obstacles ...',
        info: { attack: 3, defense: 7, magic: 7, difficulty: 8 },
        tags: ['Tank', 'Fighter'],
        partype: 'None',
        stats:
        {
            hp: 614.6,
            hpperlevel: 95,
            mp: 0,
            mpperlevel: 0,
            movespeed: 340,
            armor: 23.88,
            armorperlevel: 3.5,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 175,
            hpregen: 7.92,
            hpregenperlevel: 0.55,
            mpregen: 0,
            mpregenperlevel: 0,
            crit: 0,
            critperlevel: 0,
            attackdamage: 59.67,
            attackdamageperlevel: 3.375,
            attackspeedoffset: -0.02,
            attackspeedperlevel: 1.6
        }
    },
    {
        version: '6.24.1',
        id: 'Amumu',
        key: '32',
        name: 'Amumu',
        title: 'the Sad Mummy',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Amumu.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Amumu_0.jpg',
        blurb: '\'\'Solitude can be lonelier than death.\'\'<br><br>A lonely and melancholy soul from ancient Shurima, Amumu roams the world in search of a friend. Cursed by an ancient spell, he is doomed to remain alone forever, as his touch is death and his affection ...',
        info: { attack: 2, defense: 6, magic: 8, difficulty: 3 },
        tags: ['Tank', 'Mage'],
        partype: 'MP',
        stats:
        {
            hp: 613.12,
            hpperlevel: 84,
            mp: 287.2,
            mpperlevel: 40,
            movespeed: 335,
            armor: 23.544,
            armorperlevel: 3.8,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 125,
            hpregen: 8.875,
            hpregenperlevel: 0.85,
            mpregen: 7.38,
            mpregenperlevel: 0.525,
            crit: 0,
            critperlevel: 0,
            attackdamage: 53.384,
            attackdamageperlevel: 3.8,
            attackspeedoffset: -0.02,
            attackspeedperlevel: 2.18
        }
    },
    {
        version: '6.24.1',
        id: 'Singed',
        key: '27',
        name: 'Singed',
        title: 'the Mad Chemist',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Singed.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Signed_0.jpg',
        blurb: 'Singed descended from a long line of Zaun\'s revered chemists. Even in his youth, his talent for concocting potions far outstripped that of his peers, and he quickly distinguished himself from his less extraordinary chemist compatriots. It came as no ...',
        info: { attack: 4, defense: 8, magic: 7, difficulty: 5 },
        tags: ['Tank', 'Fighter'],
        partype: 'MP',
        stats:
        {
            hp: 542.76,
            hpperlevel: 82,
            mp: 290.6,
            mpperlevel: 45,
            movespeed: 345,
            armor: 27.88,
            armorperlevel: 3.5,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 125,
            hpregen: 8.02,
            hpregenperlevel: 0.55,
            mpregen: 7.52,
            mpregenperlevel: 0.55,
            crit: 0,
            critperlevel: 0,
            attackdamage: 62.32,
            attackdamageperlevel: 3.375,
            attackspeedoffset: 0.02,
            attackspeedperlevel: 1.81
        }
    },
    {
        version: '6.24.1',
        id: 'Blitzcrank',
        key: '53',
        name: 'Blitzcrank',
        title: 'the Great Steam Golem',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Blitzcrank.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Blitzcranck_0.jpg',
        blurb: 'Zaun is a place where both magic and science have gone awry, and the unchecked nature of experimentation has taken its toll. However, Zaun\'s lenient restrictions allow their researchers and inventors the leeway to push the bounds of science at an ...',
        info: { attack: 4, defense: 8, magic: 5, difficulty: 4 },
        tags: ['Tank', 'Fighter'],
        partype: 'MP',
        stats:
        {
            hp: 582.6,
            hpperlevel: 95,
            mp: 267.2,
            mpperlevel: 40,
            movespeed: 325,
            armor: 24.38,
            armorperlevel: 4,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 125,
            hpregen: 8.51,
            hpregenperlevel: 0.75,
            mpregen: 8.5,
            mpregenperlevel: 0.8,
            crit: 0,
            critperlevel: 0,
            attackdamage: 61.54,
            attackdamageperlevel: 3.5,
            attackspeedoffset: 0,
            attackspeedperlevel: 1.13
        }
    }];
const outputOrderDesc = [
    {
        version: '6.24.1',
        id: 'Zac',
        key: '154',
        name: 'Zac',
        title: 'the Secret Weapon',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Zac.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zac_0.jpg',
        blurb: 'Zac is the product of a Zaun experiment to manufacture a hexchem-engineered supersoldier - the Zaun Amorphous Combatant. Combining brute strength with limitless flexibility, he is a versatile juggernaut: a creative fighter who bounces over obstacles ...',
        info: { attack: 3, defense: 7, magic: 7, difficulty: 8 },
        tags: ['Tank', 'Fighter'],
        partype: 'None',
        stats:
        {
            hp: 614.6,
            hpperlevel: 95,
            mp: 0,
            mpperlevel: 0,
            movespeed: 340,
            armor: 23.88,
            armorperlevel: 3.5,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 175,
            hpregen: 7.92,
            hpregenperlevel: 0.55,
            mpregen: 0,
            mpregenperlevel: 0,
            crit: 0,
            critperlevel: 0,
            attackdamage: 59.67,
            attackdamageperlevel: 3.375,
            attackspeedoffset: -0.02,
            attackspeedperlevel: 1.6
        }
    },
    {
        version: '6.24.1',
        id: 'Singed',
        key: '27',
        name: 'Singed',
        title: 'the Mad Chemist',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Singed.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Signed_0.jpg',
        blurb: 'Singed descended from a long line of Zaun\'s revered chemists. Even in his youth, his talent for concocting potions far outstripped that of his peers, and he quickly distinguished himself from his less extraordinary chemist compatriots. It came as no ...',
        info: { attack: 4, defense: 8, magic: 7, difficulty: 5 },
        tags: ['Tank', 'Fighter'],
        partype: 'MP',
        stats:
        {
            hp: 542.76,
            hpperlevel: 82,
            mp: 290.6,
            mpperlevel: 45,
            movespeed: 345,
            armor: 27.88,
            armorperlevel: 3.5,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 125,
            hpregen: 8.02,
            hpregenperlevel: 0.55,
            mpregen: 7.52,
            mpregenperlevel: 0.55,
            crit: 0,
            critperlevel: 0,
            attackdamage: 62.32,
            attackdamageperlevel: 3.375,
            attackspeedoffset: 0.02,
            attackspeedperlevel: 1.81
        }
    },
    {
        version: '6.24.1',
        id: 'Riven',
        key: '92',
        name: 'Riven',
        title: 'the Exile',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Riven.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Riven_0.jpg',
        blurb: '\'\'There is a place between war and murder in which our demons lurk.\'\'<br><br>In Noxus, any citizen may rise to power regardless of race, gender, or social standing - strength is all that matters. It was with committed faith in this ideal that Riven ...',
        info: { attack: 8, defense: 5, magic: 1, difficulty: 8 },
        tags: ['Fighter', 'Assassin'],
        partype: 'None',
        stats:
        {
            hp: 558.48,
            hpperlevel: 86,
            mp: 0,
            mpperlevel: 0,
            movespeed: 340,
            armor: 24.376,
            armorperlevel: 3.2,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 125,
            hpregen: 5.34,
            hpregenperlevel: 0.5,
            mpregen: 0,
            mpregenperlevel: 0,
            crit: 0,
            critperlevel: 0,
            attackdamage: 56.04,
            attackdamageperlevel: 3,
            attackspeedoffset: 0,
            attackspeedperlevel: 3.5
        }
    },
    {
        version: '6.24.1',
        id: 'Morgana',
        key: '25',
        name: 'Morgana',
        title: 'Fallen Angel',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Morgana.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Morgana_0.jpg',
        blurb: 'There is a world far away populated by graceful and beautiful winged beings gifted with immortality, where an ancient conflict still rages. Like so many conflicts, this war split families. One side proclaimed themselves as beings of perfect order and ...',
        info: { attack: 1, defense: 6, magic: 8, difficulty: 1 },
        tags: ['Mage', 'Support'],
        partype: 'MP',
        stats:
        {
            hp: 547.48,
            hpperlevel: 86,
            mp: 340.8,
            mpperlevel: 60,
            movespeed: 335,
            armor: 25.384,
            armorperlevel: 3.8,
            spellblock: 30,
            spellblockperlevel: 0,
            attackrange: 450,
            hpregen: 5.705,
            hpregenperlevel: 0.6,
            mpregen: 8.5,
            mpregenperlevel: 0.8,
            crit: 0,
            critperlevel: 0,
            attackdamage: 55.46,
            attackdamageperlevel: 3.5,
            attackspeedoffset: 0,
            attackspeedperlevel: 1.53
        }
    },
    {
        version: '6.24.1',
        id: 'Blitzcrank',
        key: '53',
        name: 'Blitzcrank',
        title: 'the Great Steam Golem',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Blitzcrank.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Blitzcranck_0.jpg',
        blurb: 'Zaun is a place where both magic and science have gone awry, and the unchecked nature of experimentation has taken its toll. However, Zaun\'s lenient restrictions allow their researchers and inventors the leeway to push the bounds of science at an ...',
        info: { attack: 4, defense: 8, magic: 5, difficulty: 4 },
        tags: ['Tank', 'Fighter'],
        partype: 'MP',
        stats:
        {
            hp: 582.6,
            hpperlevel: 95,
            mp: 267.2,
            mpperlevel: 40,
            movespeed: 325,
            armor: 24.38,
            armorperlevel: 4,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 125,
            hpregen: 8.51,
            hpregenperlevel: 0.75,
            mpregen: 8.5,
            mpregenperlevel: 0.8,
            crit: 0,
            critperlevel: 0,
            attackdamage: 61.54,
            attackdamageperlevel: 3.5,
            attackspeedoffset: 0,
            attackspeedperlevel: 1.13
        }
    },
    {
        version: '6.24.1',
        id: 'Amumu',
        key: '32',
        name: 'Amumu',
        title: 'the Sad Mummy',
        img: 'https://www.masterypoints.com/assets/img/lol/champion_icons/Amumu.png',
        splash: 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Amumu_0.jpg',
        blurb: '\'\'Solitude can be lonelier than death.\'\'<br><br>A lonely and melancholy soul from ancient Shurima, Amumu roams the world in search of a friend. Cursed by an ancient spell, he is doomed to remain alone forever, as his touch is death and his affection ...',
        info: { attack: 2, defense: 6, magic: 8, difficulty: 3 },
        tags: ['Tank', 'Mage'],
        partype: 'MP',
        stats:
        {
            hp: 613.12,
            hpperlevel: 84,
            mp: 287.2,
            mpperlevel: 40,
            movespeed: 335,
            armor: 23.544,
            armorperlevel: 3.8,
            spellblock: 32.1,
            spellblockperlevel: 1.25,
            attackrange: 125,
            hpregen: 8.875,
            hpregenperlevel: 0.85,
            mpregen: 7.38,
            mpregenperlevel: 0.525,
            crit: 0,
            critperlevel: 0,
            attackdamage: 53.384,
            attackdamageperlevel: 3.8,
            attackspeedoffset: -0.02,
            attackspeedperlevel: 2.18
        }
    }];
describe('lol', () => {
    it('deberia ser una objeto', () => {
        expect(typeof lol).toBe('object');
    });
    describe('lol.filterData', () => {
        it('deberia de ser una funcion', () => {
            expect(typeof window.lol.filterData).toBe('function');
        });
        it('deberia retornar un array con los campeones segun rol', () => {
            expect(window.lol.filterData(inputFilter, filterType)).toEqual(outputFilter);
        });
    });
    describe('lol.sortData', () => {
        it('deberia de ser una funcion', () => {
            expect(typeof window.lol.sortData).toBe('function');
        });
        it('deberia retornar array campeones ordenador de forma ascendente', () => {
            expect(window.lol.sortData(inputOrder, sortByType, sortOrderAsc)).toEqual(outputOrderAsc);
        });
        it('deberia retornar array campeones ordenador de forma descendente', () => {
            expect(window.lol.sortData(inputOrder2, sortByType, sortOrderDesc)).toEqual(outputOrderDesc);
        });
    });
});